/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaz;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import libreria.Libreria;
import listaDobleLibreria.ListaLibreria;
import libros.Libros;
import listaSimpleLibros.ListaEnlazada;






/**
 *
 * @author Dell
 */

public class VentanaLibreria extends javax.swing.JFrame {
     ListaEnlazada <Libros>listalibros = new ListaEnlazada();
     Libros libro = new Libros();
    Libreria dato = new Libreria();
    ListaLibreria <Libreria>listaLibreria_1 = new ListaLibreria();
   
        
    /**
     * Creates new form VentanaLibreria
     */
    public VentanaLibreria() {
        
        initComponents();       
         jList1.setModel(modeloListaLibreria);
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Ventana de control de Libros");
        
        
        
        
         //Persistencia de datos
        
        
         //Crear un libro para añadir a listalibros
        String id = "ab 234";
        String nombreLibro = "Amanda Pasiva";
        String temaLibro = "Novela";
        String descripcion = "Amanda arreglando el celular";
        int cantidadD = 12;
        int cantV = 2;
        Double precio = 25.5;
        
        //Se asignan los datos a la clase de libro
        libro.setId(id);
        libro.setNombre(nombreLibro);
        libro.setTema(id);
        libro.setDescripción(descripcion);
        libro.setCantidadDisponibles(cantidadD);
        libro.setCantidadVendidos(cantV);
        libro.setPrecio(precio);
        
        
        
        //Se agraga el libro a la listalibros que pertenece a X libreria
        listalibros.insertarPrimero(libro);
        
        
       
       
        //Atributos
        String nombre = "SANTILLANA";
        String pais = "Costa Ria";
        int telefono = 87575754;
        String ubicacion = "Cartago";
        ListaEnlazada<Libros> Libros = listalibros;
        
        
        //Se asignan los atributos de la clase
        dato.setNombre(nombre);
        dato.setPais(pais);
        dato.setTelefono(telefono);
        dato.setUbicacion(ubicacion);
        dato.setListaLibros(Libros);
        
        
        listaLibreria_1.agregarAlFinal(dato);
        modeloListaLibreria.addElement(dato);
        
        
        
        
    }

    
    DefaultListModel modeloListaLibreria = new DefaultListModel();  
    
    public void crearLibreria(){
        ListaEnlazada <Libros> listaL = new ListaEnlazada();
        //Se agarran los datos de la caja de texto
        Libreria data=new Libreria();
        String nombre=jnombre.getText();
        String pais = jpais.getText();
        int telefono = Integer.parseInt(jtelefono.getText());;
        String  ubicacion = jTextField4.getText();
        //ListaEnlazada <Libros> libros = .getText();
        
        
        //Se asigna las variables del objeto
        data.setNombre(nombre);
        data.setPais(pais);
        data.setTelefono(telefono);
        data.setUbicacion(ubicacion);
        data.setListaLibros(listaL);
        
        
        listaLibreria_1.agregarAlFinal(data);
        modeloListaLibreria.addElement(data);
        JOptionPane.showMessageDialog(rootPane, "El registo de librería ha sido creado");
        }
    
    
    public void mostrar(){
        listaLibreria_1.mostrarListaD();
        
        
    }
    //Método eliminar librería
    public void eliminar(){
        int pos = Integer.parseInt(texto.getText());
        //listaLibreria_1.eliminarPos(pos);
        modeloListaLibreria.remove(pos);
        JOptionPane.showMessageDialog(rootPane, "El registro de librería  ha sido eliminado correctamente");
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jnombre = new javax.swing.JTextField();
        jpais = new javax.swing.JTextField();
        jtelefono = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jverlibros = new javax.swing.JButton();
        texto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jlistaL = new javax.swing.JTextField();
        jElmininar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelPais = new javax.swing.JLabel();
        jLabelTeléfono = new javax.swing.JLabel();
        jLabelUbicación = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel12.setText("Gestión de Librería");

        jnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnombreActionPerformed(evt);
            }
        });

        jpais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpaisActionPerformed(evt);
            }
        });

        jtelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtelefonoActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Pais");

        jLabel3.setText("Telefono");

        jLabel4.setText("Ubicación");

        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jButton2.setText("Mostrar en consola");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jverlibros.setText("Ver Libros");
        jverlibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jverlibrosActionPerformed(evt);
            }
        });

        texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoActionPerformed(evt);
            }
        });

        jLabel5.setText("Lista de Libros");

        jlistaL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlistaLActionPerformed(evt);
            }
        });

        jElmininar.setText("Eliminar");
        jElmininar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jElmininarActionPerformed(evt);
            }
        });

        jLabel6.setText("Resultados");

        jLabelName.setText("Nombre: ");

        jLabelPais.setText("País: ");

        jLabelTeléfono.setText("Teléfono: ");

        jLabelUbicación.setText("Ubicación: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtelefono, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jpais, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                .addComponent(jnombre, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(3, 3, 3)
                        .addComponent(jlistaL, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAgregar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jElmininar)
                                .addGap(18, 18, 18)
                                .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jButton2)
                        .addGap(119, 119, 119))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelUbicación)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jverlibros)
                        .addGap(107, 107, 107))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPais)
                            .addComponent(jLabelTeléfono))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jlistaL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAgregar))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabelName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelPais)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTeléfono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelUbicación)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jElmininar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jverlibros)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtelefonoActionPerformed
    
    }//GEN-LAST:event_jtelefonoActionPerformed

    private void jpaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpaisActionPerformed
        
    }//GEN-LAST:event_jpaisActionPerformed

    private void jnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnombreActionPerformed
        
    }//GEN-LAST:event_jnombreActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        mostrar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        // TODO add your handling code here:
        crearLibreria();
        
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jverlibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jverlibrosActionPerformed
                // TODO add your handling code here:
                 ventanaLibros vL = new ventanaLibros();
                 vL.setVisible(true);
    }//GEN-LAST:event_jverlibrosActionPerformed

    private void textoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoActionPerformed
               // TODO add your handling code here:
             
    }//GEN-LAST:event_textoActionPerformed

    private void jlistaLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlistaLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlistaLActionPerformed

    private void jElmininarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jElmininarActionPerformed
       
        eliminar();
    }//GEN-LAST:event_jElmininarActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        //RESULTADOS DE MOSTRAR LA LIBRERIA EN LAS ETIQUETAS
        int index= jList1.getSelectedIndex();
        Libreria info = (Libreria)modeloListaLibreria.getElementAt(index);
        
        jLabelName.setText("Nombre: "+info.getNombre());
        jLabelPais.setText("País: "+info.getPais());
        jLabelTeléfono.setText("Teléfono: "+info.getTelefono());
        jLabelUbicación.setText("Ubicación: "+info.getUbicacion());
    }//GEN-LAST:event_jList1ValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLibreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLibreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLibreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLibreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLibreria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jElmininar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPais;
    private javax.swing.JLabel jLabelTeléfono;
    private javax.swing.JLabel jLabelUbicación;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jlistaL;
    private javax.swing.JTextField jnombre;
    private javax.swing.JTextField jpais;
    private javax.swing.JTextField jtelefono;
    private javax.swing.JButton jverlibros;
    private javax.swing.JTextField texto;
    // End of variables declaration//GEN-END:variables
}
